language: shell

install:
  - |
    # Prepare a clean test environment
    sudo apt-get remove -y docker docker-engine docker.io docker-ce
    sudo apt-get -qq update
    sudo apt-get install -y ca-certificates gnupg curl shunit2
    sudo install -m 0755 -d /etc/apt/keyrings

  - |
    # Configure third-party package repositories
    OS_CODENAME=$(. /etc/os-release && echo "${UBUNTU_CODENAME}")

    # mongodb.org package repo
    MONGO_VERSION="${MONGO_VERSION:-8.2}"
    MONGO_MAJOR=$(echo "${MONGO_VERSION}" | cut -d '.' -f 1)
    curl -fsSL https://www.mongodb.org/static/pgp/server-${MONGO_MAJOR}.0.asc | sudo gpg -o /usr/share/keyrings/mongodb-server-${MONGO_MAJOR}.0.gpg --dearmor
    sudo rm -f /etc/apt/sources.list.d/mongodb-org-${MONGO_VERSION}.list
    echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-${MONGO_MAJOR}.0.gpg ] https://repo.mongodb.org/apt/ubuntu ${OS_CODENAME}/mongodb-org/${MONGO_VERSION} multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-${MONGO_VERSION}.list

    # docker package repo
    sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
    sudo chmod a+r /etc/apt/keyrings/docker.asc
    sudo rm -f /etc/apt/sources.list.d/docker.list
    sudo rm -f /etc/apt/sources.list.d/docker.sources
    sudo tee /etc/apt/sources.list.d/docker.sources <<EOF
    Types: deb
    URIs: https://download.docker.com/linux/ubuntu
    Suites: ${OS_CODENAME}
    Components: stable
    Signed-By: /etc/apt/keyrings/docker.asc
    EOF
    sudo apt-get -qq update

  - |
    # Install the version of docker we want to test with
    DOCKER_VERSION="${DOCKER_VERSION:-29.0.2}"
    DOCKER_PACKAGE=$(apt-cache policy docker-ce | grep ${DOCKER_VERSION} | grep -E 'Installed|Candidate' | awk '{print $2}')
    sudo apt-get install -y docker-ce=${DOCKER_PACKAGE} --allow-downgrades

  - |
    # Install the MongoDB Shell which will be compatible with the version we want to test with
    OLDER_VERSION=$(echo -e "${MONGO_VERSION}\n6.0" | sort -V | head -n1)
    if [[ "${OLDER_VERSION}" == "6.0" ]]; then
      export MONGO_SHELL="mongosh"
      sudo apt-get install -y mongodb-mongosh --allow-downgrades
    else
      export MONGO_SHELL="mongo"
      sudo apt-get install -y mongodb-org-shell=${MONGO_VERSION} --allow-downgrades
    fi

  - |
    # Build and deploy the test-stack
    docker build . -t martel/mongo-replica-ctrl:travis
    docker swarm init
    docker stack deploy -c test/docker-compose.yml ${STACK_NAME} --detach=true

script:
  - sh test/ci-test-running-basic.sh
  - sh test/ci-test-scale-basic.sh

env:
  global:
    - STACK_NAME=mongo
  matrix:
    - MONGO_VERSION=8.2 DOCKER_VERSION=29.0.2
    - MONGO_VERSION=7.0 DOCKER_VERSION=29.0.2
